backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "packages"
    label: "Packages"
    folder: "src/pages/packages"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "package"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tagline", name: "tagline", widget: "string"}
      - {label: "Cover image", name: "image", widget: "image"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Number of days", name: "lenght", widget: "string"}
      - {label: "Other text", name: "body", widget: "markdown"}

  - name: "activities"
    label: "Activities"
    folder: "src/data/activities"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "activity"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Thumbnail image", name: "image", widget: "image"}

#  pages

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/index.md"
        name: "frontpage"
        label: "Frontpage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "frontpage"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Welcoming paragraph", name: "welcome", widget: "text"}
          - {label: "Cover image", name: "image", widget: "image"}
      - file: "src/data/confirmation.md"
        name: "confirmation"
        label: "Confirmation"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "confirmation"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Cover image", name: "image", widget: "image"}
          - {label: "Body text", name: "body", widget: "markdown"}
      - file: "src/data/concept.md"
        name: "concept"
        label: "Concept"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "concept"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Cover image", name: "image", widget: "image"}
          - {label: "Body text", name: "body", widget: "markdown"}
      - file: "src/data/stories.md"
        name: "stories"
        label: "Stories"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "stories"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Welcoming paragraph", name: "welcome", widget: "text"}
          - {label: "Cover image", name: "image", widget: "image"}
      - file: "src/data/contact.md"
        name: "contact"
        label: "Contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Cover image", name: "image", widget: "image"}
          - {label: "Body text", name: "body", widget: "markdown"}
      - file: "src/data/terms.md"
        name: "terms"
        label: "Terms and Conditions"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "terms"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Cover image", name: "image", widget: "image"}
          - {label: "Body text", name: "body", widget: "markdown"}
      - file: "src/data/faq.md"
        name: "faq"
        label: "FAQ's"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "faq"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Cover image", name: "image", widget: "image"}
          - {label: "Body text", name: "body", widget: "markdown"}
    
